#Use colorgcc and C++11
import os
env = Environment(CXXFLAGS=["-std=c++0x","-march=core2"],CPPPATH='../ZKVStore',ENV =
						{'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})
#Get CLI flags
enableDebug = ARGUMENTS.get('debug', 0)
optimize = ARGUMENTS.get('optimize', 0)
if int(enableDebug):
	env.Append(CCFLAGS = '-g')

libraries = ["zmq","czmq"]

zkvSource =  ["main.cpp",
    "../ZKVStore/zutil.cpp",
    "client.cpp",
    "dbclient.cpp",
    "Status.cpp"
]

yaklibSrc = ["src/MetaRequests.cpp",
    "src/ReadRequests.cpp",
    "src/WriteRequests.cpp"
]

env.Library(target="yaklib",source=yaklibSrc,CPPPATH="include")
env.Program(target="kvc", source=zkvSource,LIBS=libraries)
