#Use colorgcc and C++11
import os
env = Environment(CXXFLAGS=["-std=c++0x","-march=core2"],CPPPATH='../ZKVStore',ENV =
						{'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

libraries = ["zmq","czmq"]

zkvSource =  ["main.cpp","../ZKVStore/zutil.cpp",
    "client.cpp"]
hello = env.Program(target="kvc", source=zkvSource,LIBS=libraries)
