#Use colorgcc and C++11
import os

cxx = ARGUMENTS.get('cxx','clang++')

env = Environment(CXX=cxx,CXXFLAGS=["-std=c++0x","-march=core2"],CPPPATH='../ZKVStore',ENV =
						{'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})
#Get CLI flags
enableDebug = ARGUMENTS.get('debug', 0)
optimize = ARGUMENTS.get('optimize', 0)
if int(enableDebug):
	env.Append(CCFLAGS = '-g')


libraries = ["zmq","czmq"]

yaklibSrc = ["src/MetaRequests.cpp",
    "src/ReadRequests.cpp",
    "src/WriteRequests.cpp",
    "src/YakClient.cpp",
    "src/Batch.cpp"
]

testSrc = [
    "test/TestGraph.cpp",
    "test/TestMain.cpp"
]

libyakclientA = env.Library(target="yakclient",source=yaklibSrc,CPPPATH="include")
libyakclientSO = env.SharedLibrary(target="yakclient",source=yaklibSrc,CPPPATH="include")
env.Program(target="yakctest",source=testSrc, CPPPATH="include", LIBS=["boost_unit_test_framework",libyakclientA,"zmq","czmq"],LDPATH="../clientbuild")
env.Install("/usr/local/lib", libyakclientA)
env.Install("/usr/local/lib", libyakclientSO)
env.Alias('install', '/usr/local/lib')
#env.Program(target="kvc", source=zkvSource,LIBS=libraries)

