#Use colorgcc and C++11
import os

linkmode = ARGUMENTS.get("link","dynamic")

linkflags=[]
cxxflags=["-std=c++0x","-march=core2","-Wall"]
if linkmode == "static":
    cxxflags.append("-static")
    linkflags.append("-static")
elif linkmode == "dynamic":
    pass
else:
    raise Exception("Error: Link mode %s invalid!" % link)

enableDebug = ARGUMENTS.get('debug', 0)
if int(enableDebug):
    cxxflags.append('-g')

linkflags.append("-pthread")
linkflags.append("-Wl,-rpath=.")
#linkflags.append("-static-libgcc")

env = Environment(CXXFLAGS=cxxflags,
                  LINKFLAGS=linkflags,
                  ENV = {'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

malloc = ARGUMENTS.get("malloc","jemalloc")
libraries = ["zmq","czmq","leveldb","boost_program_options",malloc]
if linkmode == "static":
    #Somehow we need this
    libraries.append("snappy")
    #libraries.append("unwind")

zkvSource =  ["zutil.cpp",
    "FileUtils.cpp",
    "main.cpp",
    "TableOpenHelper.cpp",
    "ConfigParser.cpp",
    "Tablespace.cpp",
    "UpdateWorker.cpp",
    "ReadWorker.cpp",
    "Logger.cpp",
    "LogServer.cpp",
    "LogSinks.cpp",
    "AbstractFrameProcessor.cpp",
    "AsyncJobRouter.cpp",
    "ClientSidePassiveJob.cpp",
    "SequentialIDGenerator.cpp",
    "Server.cpp",
    "HTTPServer.cpp"]
hello = env.Program(target="zkv", source=zkvSource,LIBS=libraries)
