env = Environment()   # Create an environmnet

zkvSource =  ["zutil.cpp",
    "main.cpp",
    "TableOpenHelper.cpp",
    "Tablespace.cpp",
    "UpdateWorker.cpp"]
hello = env.Program(target="zkv", source=zkvSource)
