#Use colorgcc and C++11
import os
env = Environment(CXXFLAGS=["-std=c++0x","-march=core2"],ENV =
						{'PATH' : os.environ['PATH'],
                         'TERM' : os.environ['TERM'],
                         'HOME' : os.environ['HOME']})

libraries = ["zmq","czmq","leveldb","jemalloc"]

zkvSource =  ["zutil.cpp",
    "main.cpp",
    "TableOpenHelper.cpp",
    "Tablespace.cpp",
    "UpdateWorker.cpp",
    "ReadWorker.cpp",
    "Logger.cpp",
    "LogServer.cpp",
    "Server.cpp"]
hello = env.Program(target="zkv", source=zkvSource,LIBS=libraries)
