env = Environment(CXXFLAGS=["-std=c++0x","-march=core2"])   # Create an environmnet

libraries = ["zmq","czmq","leveldb"]

zkvSource =  ["zutil.cpp",
    "main.cpp",
    "TableOpenHelper.cpp",
    "Tablespace.cpp",
    "UpdateWorker.cpp",
    "ReadWorker.cpp",
    "Server.cpp"]
hello = env.Program(target="zkv", source=zkvSource,LIBS=libraries)
